mlr-org/mlrMBO

- R/MBOResult.R
- R/TuningProblem.R
- R/TuningResult.R
- R/TuningState.R
- R/evalFinalPoint.R
- R/evalTargetFun.R
- R/generateMBODesign.R
- R/makeMBOControl.R
- R/mbo.R
- R/mboContinue.R
- R/mboTemplate.R
- R/proposePoints.R
- R/shouldTerminate.R
- R/utils.R
- man/MBOMultiObjResult.Rd
- man/MBOSingleObjResult.Rd
- man/makeMBOControl.Rd
- tests/testthat/test_mbo.R
- tests/testthat/test_stopping_criteria.R
Big changes under the hood - allowing friendlier step by step iteration.
Still to do:
* documentation
* cleaning up the code
> OOP Refacturing

- R/OptProblem.R
- R/OptResult.R
- R/OptState.R
- R/OptState_getter.R
- R/OptState_setter.R
- R/infillOptCMAES.R
- R/infillOptEA.R
- R/infillOptFocus.R
- R/infillOptNSGA2.R
- R/infill_crits.R
- R/mboFinalize.R
- R/mboMultiFid_helpers.R
- R/mboMultiFid_learner.R
- R/multicrit_helpers.R
- R/proposePoints.R
- R/proposePointsByInfillOptimization.R
- R/proposePointsConstantLiar.R
- R/proposePointsDIB.R
- R/proposePointsMOIMBO.R
- R/proposePointsMSPOT.R
- R/proposePointsParEGO.R
- R/proposePointsParallelLCB.R
- R/proposePointsRandom.R
- R/renderExampleRunPlotMultiCrit.R
- R/renderExampleRunPlotSingleCrit1d.R
- R/renderExampleRunPlotSingleCrit2d.R
- R/shouldTerminate.R
- README.md
- tests/testthat/test_multifid.R
Following changes
* proposePoints nearly only dependent on opt.state
* OptState now has a time.model
* MultiFid can use time.model
* all infill functions use model**s** consistently, which is a list with one item if its only one model
> opt.state integration, time.model

- R/exampleRun.R
- tests/testthat/test_exampleRun.R
Travis will fail because of Issue #134
> exampleRun handles trafos, cleaned up (Fixes #122)

- R/OptProblem.R
- R/OptState_setter.R
- R/generateMBODesign.R
- R/mbo.R
- R/mboFinalize.R
- R/mboTemplate.R
- R/proposePoints.R
Please let me now if you have further questions to be answered in the code or specific requests how to document.
> mboLoop: documentation and clean-up (Issue #131)

- R/evalTargetFun.R
- R/makeMBOControl.R
- R/mbo.R
- R/mboFinalize.R
- tests/testthat/test_mbo_km.R
> Remove configuremlr

- R/exampleRun.R
- R/mbo.R
- man/exampleRun.Rd
- man/makeMBOControl.Rd
- man/mbo.Rd
I found the documentation to be quite sufficient. Added the levels to be a bit more concrete. Do we want an example?
> Work on Issue #161, brief description of parallelMap levels

- R/OptProblem.R
- R/OptResult.R
- R/OptState.R
- R/evalTargetFun.R
- R/makeMBOOptPath.R
If something is missing, let me know
> Documentation on Opt* and cleanup (Hopefully Fixes #166)

- R/doc_mbo_parallel.R
- R/exampleRun.R
- R/zzz.R
- man/exampleRun.Rd
- man/mbo_parallel.Rd
Hopefully now it's fine - don't know about @berndbischl changes in doc_mbo_parallel.R
> remove mlrMBO.true.feval from parallelMap levels

- inst/examples/ex_1d_discrete_noisy.R
- inst/examples/ex_1d_noisy_numeric.R
- inst/examples/ex_1d_noisy_numeric_multifid.R
- inst/examples/ex_1d_numeric.R
- inst/examples/ex_1d_numeric_multipoint.R
- inst/examples/ex_2d_numeric.R
- inst/examples/ex_2d_numeric_multipoint.R
- inst/examples/ex_mixed.R
- inst/examples/ex_multicrit.R
- inst/examples/ex_multicrit_plots.R
- tests/testthat/test_multifid.R
changes were necessary because auf smoof and generateDesign externalization
> fixed multifid and examples

- R/setMBOControlTermination.R
- R/term_conds.R
Just a suggestion open for discussion
> rename makeMBO*Termination to makeMBOTermination*

- R/checkStuff.R
Added check for noisy multicrit. Stop with error message in this case (fixes #82).
> add check for currently unsipported noisy multicrit funs

- R/doc_mbo_OptPath.R
- R/evalTargetFun.R
- R/filterProposedPoints.R
- R/getExtras.R
- R/getInfillCritFunction.R
- R/proposePointsByInfillOptimization.R
- R/proposePointsHelpers.R
- R/proposePointsMOIMBO.R
- R/proposePointsMSPOT.R
- R/proposePointsRandom.R
- man/mbo_OptPath.Rd
- todo-files/ex_multifid_1.R
* added prop.type column to optPath
* named stuff as discussed in #149 
* documented possible prop.type values in optpath docs
> Fix149 proposed points type in optpath

- R/OptProblem.R
- R/checkLearner.R
- R/mbo.R
- man/mbo.Rd
Really minor fixes on Issue #204 and #190. You have one week for veto before I will auto-merge :wink:
> Minor fixes

- src/quickstart.Rmd
todo: mention init design points
> new functions used

- R/exampleRun.R
- inst/examples/ex_1d_noisy_numeric.R
- inst/examples/ex_1d_noisy_numeric_multifid.R
changes went undetected here as it seems
> fix broken multifid example plot

- R/mbo.R
- man/exampleRun.Rd
- man/exampleRunMultiCrit.Rd
- man/mbo.Rd
> Fix 235 default design

- R/OptProblem.R
- tests/testthat/helper_objects.R
- tests/testthat/test_different_learners.R
- tests/testthat/test_impute_y.R
- tests/testthat/test_infill_opt_ea.R
- tests/testthat/test_infill_opt_focus.R
- tests/testthat/test_infillcrits.R
- tests/testthat/test_initdesign.R
- tests/testthat/test_mboContinue.R
- tests/testthat/test_mboFinalize.R
- tests/testthat/test_mbo_km.R
- tests/testthat/test_mbo_kmforrester.R
- tests/testthat/test_mbo_rf.R
- tests/testthat/test_multipoint_multicrit.R
- tests/testthat/test_optpath_extras.R
- tests/testthat/test_plotEAF.R
- tests/testthat/test_plot_MBOResult.R
> Fix get param set generic

- R/doc_mbo_OptPath.R
- R/getExtras.R
- R/renderExampleRunPlot_helpers.R
- inst/examples/ex_multicrit.R
- man/mbo_OptPath.Rd
- tests/testthat/helper_zzz.R
- tests/testthat/test_multicrit_parego.R
> renamed .weight to parEGOweight

- R/mbo.R
- R/plotExampleRun.R
- man/exampleRun.Rd
- man/exampleRunMultiCrit.Rd
- man/mbo.Rd
- man/plotExampleRun.Rd
This PR is just to remind you that we are working on the documentation in the branch **manpages** this is ongoing work. 
But a reviewer is always asked to merge if the current status is fine.
> Overhaul of manpages

- R/MBOResult.R
- R/OptState.R
- R/mboTemplate.R
- R/setMBOControlTermination.R
- R/shouldTerminate.R
- R/term_conds.R
- man/MBOSingleObjResult.Rd
- man/setMBOControlTermination.Rd
- tests/testthat/test_termination_criteria.R
It always bothered me that we don't have a unified naming of the termination criteria so I changed that. Hopefully in the favor of everyone.
> abolish stopping in favor of termination

- inst/examples/ex_multicrit_plots.R
Since 3D is strange and we will change it some time in the future
> fix example of plot multicrit

- R/checkStuff.R
- R/getSupportedMultipointInfillOptFunctions.R
- R/proposePoints.R
- R/proposePointsMOIMBO.R
- R/renderExampleRunPlotSingleCrit1d.R
- R/renderExampleRunPlotSingleCrit2d.R
- R/setMBOControlMultiPoint.R
- inst/examples/ex_1d_numeric_multipoint.R
- inst/examples/ex_2d_numeric_multipoint.R
- tests/testthat/test_exampleRun.R
- tests/testthat/test_multipoint_multicrit.R
Please check if everything makes sense now, namewise.
This should be the proposal by @berndbischl in #133
> rename multipoint.multicrit to moimbo

- R/setMBOControlInfill.R
- tests/testthat/test_infillcrits.R
> add explicit conversion of infill crit to character

- R/makeMboLearner.R
- R/setMBOControlInfill.R
- man/mbo.Rd
- man/setMBOControlInfill.Rd
- tests/testthat/helper_objects.R
- tests/testthat/test_different_learners.R
- tests/testthat/test_exampleRun.R
- tests/testthat/test_infill_opt_ea.R
- tests/testthat/test_multipoint_cb.R
- tests/testthat/test_multipoint_cl.R
- tests/testthat/test_multipoint_moimbo.R
Started to fix some warnings reported in #292
> get rid of some testthat warnings

- R/renderExampleRunPlotSingleCrit2d.R
Remove unneccessary aestethics.
Fixes all remaining ggplot-regarded warnings.
> fix ggplot2 warnings

- R/getExtras.R
- R/makeMBOLearner.R
- R/setMBOControlMultiPoint.R
- inst/examples/ex_1d_numeric_multipoint.R
- man/makeMBOLearner.Rd
- man/setMBOControlMultiPoint.Rd
- tests/testthat/test_exampleRun.R
- tests/testthat/test_multipoint_moimbo.R
This should fix #314 
In case of moimbo we just ignore the infill crit components.
> Fix 314 Extras for moimbo

- R/makeMBOLearner.R
Could also be checked in mlr maybe.
> Proposal to fix issue #327

- R/infill_crits.R
- R/makeMBOInfillCriterion.R
- R/zzz.R
- tests/testthat/test_infillcrits.R
> fix minor stuff in infill crits

- .travis.yml
- R/makeMBOInfillCriterion.R
Should not pass travis until [this PR in BBmisc](https://github.com/berndbischl/BBmisc/pull/70) is merged.
> use convertToShortString instead of own function

- R/infill_crits.R
- tests/testthat/test_infillcrits.R
Fix for issue #360. Classic missing `drop=FALSE`
> fix eqi not working for 1D

- R/renderExampleRunPlotSingleCrit.R
- R/renderExampleRunPlotSingleCrit1d.R
- R/setMBOControlMultiObj.R
- R/term_conds.R
- todo-files/exampleRun_plot.R
> use asInt(eger) consequenatally

- R/checkLearner.R
- R/exampleRun.R
- R/exampleRunMultiObj.R
- R/makeMBOLearner.R
- R/mbo.R
- man/exampleRun.Rd
- man/exampleRunMultiObj.Rd
- man/makeMBOLearner.Rd
- tests/testthat/test_mbo_km.R
> pass show.info to show.learner.output (Fixes #378)

- README.md
- inst/CITATION
#364 
@berndbischl @danielhorn: Can you check if the citing publications are correct?
> add citation information

- R/checkStuff.R
> add check for non-box-constraints

- R/MBOResult.R
- R/OptState_getter.R
- R/evalFinalPoint.R
- R/evalProposedPoints.R
- R/getExtras.R
- R/makeProposal.R
- R/proposePointsByInfillOptimization.R
- R/proposePointsHelpers.R
- R/proposePointsMOIMBO.R
- R/proposePointsMSPOT.R
- R/proposePointsRandom.R
- tests/testthat/test_mbo_km.R
This PR fixes issue #302 by having consistant handling of Proposals
> Introduce Proposals, Fixes Issue #302

- DESCRIPTION
...and EGO in Description.
What do you think?
> Mention Bayesian Optimization in title

- vignettes/supplementary/noisy_optimization.Rmd
I fixed a missing \frac in a formula.
> Add missing \frac

- R/setMBOControlTermination.R
> add assertion for MBOControl

- R/SMBO.R
- tests/testthat/test_smbo.R
> Keep user extras in OptPath

- R/checkStuff.R
- tests/testthat/test_multipoint_cl.R
> allow aei and cl multipoint

- DESCRIPTION
- tests/testthat.R
- tests/testthat/test_infillcrits.R
- tests/testthat/test_initCrit.R
- tests/testthat/test_multiobj_dib.R
added skip covr for problematic test
> Fix coverage

- R/setMBOControlInfill.R
fixes #472 numeric -> int type
> Correct parameter types for setMBOControlInfill

- R/proposePointsMOIMBO.R
Hopefully this somehow fixes the problem. But I am not sure if it works correctly on integer values (methodology-wise).
Hopefully solves Issue #392
> MOIMBO: ensure matrix is numeric (Fixes #392)

- R/SMBO.R
- R/infill_crits.R
> Fix SMBO in combination with Adaptive Infill Criteria

- R/infillOptNSGA2.R
fixes #477 nsga2, which used wrong dots
> Remove fron dots in nsga2
